# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute growth coordinate matrices
#'
#' Transforms growth matrix into coordinate format matrix in terms of CBM pools.
#'
#' @param pn `PoolNames` object
#' @param growthIncrements Matrix of growth increments
#'
#' @name ComputeGrowthCoordinateMatrices
#' @rdname ComputeGrowthCoordinateMatrices
NULL

#' Compute overmature decline coordinate matrices
#'
#' Transforms overmature decline matrix into coordinate format matrix in terms of CBM pools.
#'
#' @param pn `PoolNames` object
#' @param decline Matrix containing proportion decline for each pool
#'
#' @name ComputeOverMatureDeclineCoordinateMatrices
#' @rdname ComputeOverMatureDeclineCoordinateMatrices
NULL

#' Compute growth and decline matrices
#'
#' DESCRIPTION NEEDED
#'
#' @param growthIncrements Matrix of growth increments
#' @param decline Matrix containing proportion decline for each pool
#'
#' @name ComputeGrowthAndDeclineMatrices
#' @rdname ComputeGrowthAndDeclineMatrices
NULL

#' Step through pools, computing carbon transfers
#'
#' Computes by row (stand/`pixelGroup`) across all columns (pools) in place.
#'
#' @param pools A numeric matrix describing the amount of carbon in each pool (column) across
#'              multiple stands/pixel groups (rows).
#' @param opMatrix A numeric matrix with columns corresponding to flows, and rows corresponding
#'                 to stands/pixel groups. Values are indices into the `flowMatrices`.
#' @param flowMatrices A list of lists (or environments) containing all carbon flow matrices.
#'
#' @export
StepPoolsRef <- function(pools, opMatrix, flowMatrices) {
    invisible(.Call(`_carbonara_StepPoolsRef`, pools, opMatrix, flowMatrices))
}

#' Step through pools, computing carbon transfers
#'
#' Computes by row (stand/`pixelGroup`) across all columns (pools).
#'
#' @inheritParams StepPoolsRef
#'
#' @export
#'
#' @examples
#' nPixGrp <- 3
#'
#' pools <- matrix(c(1.0, 10.0, 0.0, 1.0, 20.0, 0.0, 1.0, 5.0, 0.0),
#'                 ncol = 3, nrow = nPixGrp, byrow = TRUE)
#' colnames(pools) <- c("input", "pool1", "pool2")
#' pools
#'
#' ##      input pool1 pool2
#' ## [1,]     1    10     0
#' ## [2,]     1    20     0
#' ## [3,]     1     5     0
#'
#' op <- matrix(rep(c(1, 1), nPixGrp), ncol = 2, nrow = nPixGrp, byrow = TRUE)
#' colnames(op) <- c("disturbance", "growth")
#'
#' cnames <- c("row", "col", "value")
#' dist <- matrix(c(2, 3, 1, 1, 1, 1), ncol = 3, nrow = 2, byrow = TRUE)
#' colnames(dist) <- cnames
#' grow <- matrix(c(1, 2, 0.1, 1, 3, 0.2, 2, 3, 0.3, 3, 3, 1.0), ncol = 3, nrow = 4, byrow = TRUE)
#' colnames(grow) <- cnames
#' flow <- list(Disturbance = list(dist), Growth = list(grow))
#'
#' new_pools <- StepPools(pools, op, flow)
#' new_pools
#'
#' ##      input pool1 pool2
#' ## [1,]     1   0.1  10.2
#' ## [2,]     1   0.1  20.2
#' ## [3,]     1   0.1   5.2
#'
StepPools <- function(pools, opMatrix, flowMatrices) {
    .Call(`_carbonara_StepPools`, pools, opMatrix, flowMatrices)
}

#' Compute overmature decline
#'
#' Compute flows to dom pools that occur on a growth curve decline.
#'
#' @param growthIncrements Matrix of growth increments
#' @param turnoverParams `data.frame` specifying turnover parameters
#'
#'@export
ComputeOvermatureDecline <- function(growthIncrements, turnoverParams) {
    .Call(`_carbonara_ComputeOvermatureDecline`, growthIncrements, turnoverParams)
}

#' Compute growth increments
#'
#' Compute the total growth (above ground and belowground) increment matrices for all
#' stands based on age and hashtable of growth increments by growth curve id.
#'
#' @param growthIncrements a hash table of growth increments by `gcid`, by `age`
#' @param ages the stand age, (the inventory age) stands will be simulated to this age in the final pass
#' @param gcids DESCRIPTION NEEDED
#' @param pools DESCRIPTION NEEDED
#' @param rootParameters `data.frame` (DESCRIPTION NEEDED)
#' @param biomassToCarbonRate DESCRIPTION NEEDED
#' @param swMult softwood multiplier? (DESCRIPTION NEEDED)
#' @param hwMult hardwood multiplier? (DESCRIPTION NEEDED)
#'
#'@export
ComputeGrowthIncrements <- function(growthIncrements, ages, gcids, pools, rootParameters, biomassToCarbonRate, swMult = 1.0, hwMult = 1.0) {
    .Call(`_carbonara_ComputeGrowthIncrements`, growthIncrements, ages, gcids, pools, rootParameters, biomassToCarbonRate, swMult, hwMult)
}

#'@export
ComputeGrowthAndDeclineMatrices <- function(growthIncrements, decline) {
    .Call(`_carbonara_ComputeGrowthAndDeclineMatrices`, growthIncrements, decline)
}

#' Compute growth and decline matrices
#'
#' DESCRIPTION NEEDED
#'
#' @param growthIncrements a hash table of growth increments by `gcid`, by `age`
#' @param ages the stand age, (the inventory age) stands will be simulated to this age in the final pass
#' @param gcids integer vector of growth curve ids
#' @param pools Matrix (DESCRIPTION NEEDED)
#' @param rootParameters `data.frame` specifying root parameters
#' @param turnoverParams `data.frame specifying turnover parameters
#' @param biomassToCarbonRate numeric DESCRIPTION NEEDED
#' @param swMult softwood multiplier? (DESCRITION NEEDED)
#' @param hwMult hardwood multiplier? (DESCRITION NEEDED)
#'
#' @name ComputeGrowthAndDeclineMatrices2
#' @rdname ComputeGrowthAndDeclineMatrices2
#'
#' @export
ComputeGrowthAndDeclineMatrices2 <- function(growthIncrements, ages, gcids, pools, rootParameters, turnoverParams, biomassToCarbonRate, swMult = 1.0, hwMult = 1.0) {
    .Call(`_carbonara_ComputeGrowthAndDeclineMatrices2`, growthIncrements, ages, gcids, pools, rootParameters, turnoverParams, biomassToCarbonRate, swMult, hwMult)
}

#' Spinup
#'
#' Spinup a landscape by running rotations of stand replacing disturbances repeatedly until the
#' pre-disturbance slow pools and the last rotation pre-disturbance slow pools are within a tolerance.
#' Stand then grows to inventory age, and is ready for CBM simulation.
#'
#' @param pools Matrix (DESCRIPTION NEEDED)
#' @param opMatrix Matrix DESCRIPTION NEEDED
#' @param constantProcesses a list of constant process C dynamics matrices
#' @param growthIncrements a hash table of growth increments by `gcid`, by `age`
#' @param ages the stand age, (the inventory age) stands will be simulated to this age in the final pass
#' @param gcids the growth curve ids (referenced by `growthIncrements`)
#' @param historicdmids DESCRIPTION NEEDED
#' @param lastPassdmids DESCRIPTION NEEDED
#' @param delays DESCRIPTION NEEDED
#' @param minRotations DESCRIPTION NEEDED
#' @param maxRotations DESCRIPTION NEEDED
#' @param returnIntervals DESCRIPTION NEEDED
#' @param rootParameters `data.frame` specifying root parameters
#' @param turnoverParams `data.frame` specifying turnover parameters
#' @param biomassToCarbonRate DESCRIPTION NEEDED
#' @param debug logical indicating whether to run spinup in debug mode.
#'
#' @export
Spinup <- function(pools, opMatrix, constantProcesses, growthIncrements, ages, gcids, historicdmids, lastPassdmids, delays, minRotations, maxRotations, returnIntervals, rootParameters, turnoverParams, biomassToCarbonRate, debug = FALSE) {
    .Call(`_carbonara_Spinup`, pools, opMatrix, constantProcesses, growthIncrements, ages, gcids, historicdmids, lastPassdmids, delays, minRotations, maxRotations, returnIntervals, rootParameters, turnoverParams, biomassToCarbonRate, debug)
}

