# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute growth coordinate matrices
#'
#' Transforms growth matrix into coordinate format matrix in terms of CBM pools.
#'
#' @param pn `PoolNames` object
#' @param growthIncrements Matrix of growth increments
#'
#' @name ComputeGrowthCoordinateMatrices
#' @rdname ComputeGrowthCoordinateMatrices
NULL

#' Compute overmature decline coordinate matrices
#'
#' Transforms overmature decline matrix into coordinate format matrix in terms of CBM pools.
#'
#' @param pn `PoolNames` object
#' @param decline Matrix containing proportion decline for each pool
#'
#' @name ComputeOverMatureDeclineCoordinateMatrices
#' @rdname ComputeOverMatureDeclineCoordinateMatrices
NULL

#' `StepPoolsRef`
#'
#' DESCRIPTION NEEDED
#'
#' @param pools DESCRIPTION NEEDED
#' @param opMatrix DESCRIPTION NEEDED
#' @param flowMatrices DESCRIPTION NEEDED
#'
StepPoolsRef <- function(pools, opMatrix, flowMatrices) {
    invisible(.Call('_carbonara_StepPoolsRef', PACKAGE = 'carbonara', pools, opMatrix, flowMatrices))
}

#' `StepPools`
#'
#' DESCRIPTION NEEDED
#'
#' @param pools DESCRIPTION NEEDED
#' @param opMatrix DESCRIPTION NEEDED
#' @param flowMatrices DESCRIPTION NEEDED
#'
#' @export
StepPools <- function(pools, opMatrix, flowMatrices) {
    .Call('_carbonara_StepPools', PACKAGE = 'carbonara', pools, opMatrix, flowMatrices)
}

#' Compute overmature decline
#'
#' Compute flows to dom pools that occur on a growth curve decline.
#'
#' @param growthIncrements Matrix of growth increments
#' @param turnoverParams `data.frame` specifying turnover parameters
#'
ComputeOvermatureDecline <- function(growthIncrements, turnoverParams) {
    .Call('_carbonara_ComputeOvermatureDecline', PACKAGE = 'carbonara', growthIncrements, turnoverParams)
}

#' Compute growth increments
#'
#' Compute the total growth (above ground and belowground) increment matrices for all
#' stands based on age and hashtable of growth increments by growth curve id.
#'
#' @param growthIncrements a hash table of growth increments by `gcid`, by `age`
#' @param ages the stand age, (the inventory age) stands will be simulated to this age in the final pass
#' @param gcids DESCRIPTION NEEDED
#' @param pools DESCRIPTION NEEDED
#' @param rootParameters `data.frame` (DESCRIPTION NEEDED)
#' @param biomassToCarbonRate DESCRIPTION NEEDED
#' @param swMult softwood multiplier? (DESCRIPTION NEEDED)
#' @param hwMult hardwood multiplier? (DESCRIPTION NEEDED)
#'
ComputeGrowthIncrements <- function(growthIncrements, ages, gcids, pools, rootParameters, biomassToCarbonRate, swMult = 1.0, hwMult = 1.0) {
    .Call('_carbonara_ComputeGrowthIncrements', PACKAGE = 'carbonara', growthIncrements, ages, gcids, pools, rootParameters, biomassToCarbonRate, swMult, hwMult)
}

#' Compute growth and decline matrices
#'
#' DESCRIPTION NEEDED
#'
#' @param growthIncrements Matrix of growth increments
#' @param decline Matrix containing proportion decline for each pool
#'
#' @name ComputeGrowthAndDeclineMatrices
#' @rdname ComputeGrowthAndDeclineMatrices
ComputeGrowthAndDeclineMatrices <- function(growthIncrements, decline) {
    .Call('_carbonara_ComputeGrowthAndDeclineMatrices', PACKAGE = 'carbonara', growthIncrements, decline)
}

#' Compute growth and decline matrices
#'
#' DESCRIPTION NEEDED
#'
#' @param growthIncrements a hash table of growth increments by `gcid`, by `age`
#' @param ages the stand age, (the inventory age) stands will be simulated to this age in the final pass
#' @param gcids integer vector of growth curve ids
#' @param pools Matrix (DESCRIPTION NEEDED)
#' @param rootParameters `data.frame` specifying root parameters
#' @param turnoverParams `data.frame specifying turnover parameters
#' @param biomassToCarbonRate numeric DESCRIPTION NEEDED
#' @param swMult softwood multiplier? (DESCRITION NEEDED)
#' @param hwMult hardwood multiplier? (DESCRITION NEEDED)
#'
#' @export
#' @name ComputeGrowthAndDeclineMatrices2
#' @rdname ComputeGrowthAndDeclineMatrices2
ComputeGrowthAndDeclineMatrices2 <- function(growthIncrements, ages, gcids, pools, rootParameters, turnoverParams, biomassToCarbonRate, swMult = 1.0, hwMult = 1.0) {
    .Call('_carbonara_ComputeGrowthAndDeclineMatrices2', PACKAGE = 'carbonara', growthIncrements, ages, gcids, pools, rootParameters, turnoverParams, biomassToCarbonRate, swMult, hwMult)
}

#' Spinup
#'
#' Spinup a landscape by running rotations of stand replacing disturbances repeatedly until the
#' pre-disturbance slow pools and the last rotation pre-disturbance slow pools are within a tolerance.
#' Stand then grows to inventory age, and is ready for CBM simulation.
#'
#' @param pools Matrix (DESCRIPTION NEEDED)
#' @param opMatrix Matrix DESCRIPTION NEEDED
#' @param constantProcesses a list of constant process C dynamics matrices
#' @param growthIncrements a hash table of growth increments by `gcid`, by `age`
#' @param ages the stand age, (the inventory age) stands will be simulated to this age in the final pass
#' @param gcids the growth curve ids (referenced by `growthIncrements`)
#' @param historicdmids DESCRIPTION NEEDED
#' @param lastPassdmids DESCRIPTION NEEDED
#' @param delays DESCRIPTION NEEDED
#' @param minRotations DESCRIPTION NEEDED
#' @param maxRotations DESCRIPTION NEEDED
#' @param returnIntervals DESCRIPTION NEEDED
#' @param rootParameters `data.frame` specifying root parameters
#' @param turnoverParams `data.frame` specifying turnover parameters
#' @param biomassToCarbonRate DESCRIPTION NEEDED
#' @param debug logical indicating whether to run spinup in debug mode.
#'
#' @export
Spinup <- function(pools, opMatrix, constantProcesses, growthIncrements, ages, gcids, historicdmids, lastPassdmids, delays, minRotations, maxRotations, returnIntervals, rootParameters, turnoverParams, biomassToCarbonRate, debug = FALSE) {
    .Call('_carbonara_Spinup', PACKAGE = 'carbonara', pools, opMatrix, constantProcesses, growthIncrements, ages, gcids, historicdmids, lastPassdmids, delays, minRotations, maxRotations, returnIntervals, rootParameters, turnoverParams, biomassToCarbonRate, debug)
}

